name: Franzo
description: Final Year Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  image_picker: ^0.6.6+5
  cupertino_icons: 0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6 
  scoped_model: 1.0.1
  firebase_storage: 3.1.5
  shared_preferences: 0.5.6+3
  pin_code_text_field: 1.5.1
  marquee: ^1.3.1
  carousel_slider: ^2.1.0
  random_string: ^2.0.1
  intl: ^0.16.1
  launch_review: ^2.0.0
  share: ^0.6.4+3
  geolocator: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/FRANZO.png
   - assets/images/Logo.png
   - assets/images/auth.png
   - assets/images/carousel/furniture.jpg
   - assets/images/carousel/pest.jpg
   - assets/images/carousel/pipe.jpg
   - assets/images/carousel/room.jpg
   - assets/images/listing/electric.jpg
   - assets/images/listing/electronic.jpg
   - assets/images/listing/grooming.jpg
   - assets/images/listing/room.jpg
   - assets/images/defaultpp.png
